defaultPlacement: end
enableVersioning: true
handle: documents
name: Documents
propagationMethod: all
siteSettings:
  b158c1f2-fbd0-44ab-9d78-2fd2c6115e8b: # cardock
    enabledByDefault: true
    hasUrls: true
    template: documents/_entry
    uriFormat: 'documents/{slug}'
type: channel
