defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  b158c1f2-fbd0-44ab-9d78-2fd2c6115e8b: # cardock
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
